ktor:
    application:
        modules:
            - cn.straosp.jotting.server.ApplicationKt.module
    deployment:
        port: 8080

headerFile: /Users/straosp/Project/ktor/JottingServer/static/header

